version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: fd__mysql_8_0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: garcolkey
      MYSQL_ROOT_HOST: 172.20.0.1
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3308:3306